In [1]:
# Import Dataset
from pathlib import Path
import pandas as pd

# Project root directory
ROOT_DIR = Path.cwd().parent

# Merged Dataset 
DATASET_PATH = ROOT_DIR / "Datasets"  / "merged" / "crypto_master.csv"

df = pd.read_csv(DATASET_PATH)
df.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Crypto
0,1,Aave,AAVE,2020-10-05 23:59:59,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07,Aave
1,2,Aave,AAVE,2020-10-06 23:59:59,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07,Aave
2,3,Aave,AAVE,2020-10-07 23:59:59,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07,Aave
3,4,Aave,AAVE,2020-10-08 23:59:59,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08,Aave
4,5,Aave,AAVE,2020-10-09 23:59:59,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08,Aave

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37082 entries, 0 to 37081
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SNo        37082 non-null  int64
 1   Name       37082 non-null  str
 2   Symbol     37082 non-null  str
 3   Date       37082 non-null  str
 4   High       37082 non-null  float64
 5   Low        37082 non-null  float64
 6   Open       37082 non-null  float64
 7   Close      37082 non-null  float64
 8   Volume     37082 non-null  float64
 9   Marketcap  37082 non-null  float64
 10  Crypto     37082 non-null  str
dtypes: float64(6), int64(1), str(4)
memory usage: 4.4 MB

In [3]:
# TO Date datatype
df['Date'] = pd.to_datetime(df['Date'])

instead of deleting the zero volume and marketcap columns I am going to create a new column named is_zero_volume and is_zero_marketcap.

In [4]:
# Create boolean columns for zero volume and zero market cap
df['is_zero_volume'] = df['Volume'] == 0
df['is_zero_marketcap'] = df['Marketcap'] == 0

In [5]:
# Delete serial number
df = df.drop(columns = ['SNo'])

In [6]:
df.head()

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Crypto,is_zero_volume,is_zero_marketcap
0,Aave,AAVE,2020-10-05 23:59:59,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07,Aave,True,False
1,Aave,AAVE,2020-10-06 23:59:59,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07,Aave,False,False
2,Aave,AAVE,2020-10-07 23:59:59,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07,Aave,False,False
3,Aave,AAVE,2020-10-08 23:59:59,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08,Aave,False,False
4,Aave,AAVE,2020-10-09 23:59:59,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08,Aave,False,False

For now let's ignore the date inconsistency I beleve it doesn't gonna effect our analysis.

In [7]:
CLEANED_DATASET_PATH = ROOT_DIR / "Datasets" / "cleaned" / "crypto_master_cleaned.csv"

df.to_csv(CLEANED_DATASET_PATH, index=False)
print("dataset updated successfully.")

dataset updated successfully.